uint16 DEFAULT              = 0

#---system---
uint16 SYSTEM_ON            = 1
uint16 SYSTEM_OFF           = 2
uint16 LOG_FAILED           = 3

#    sensor
uint16 TOUCH_HEAD           = 5

#    power
uint16 LOW_POWER            = 10
uint16 CHARGING             = 11
uint16 CHARGED              = 12



#    blue
uint16 BLUE_FAILED          = 15

#    wifi
uint16 WIFI_SUCCEED         = 20

#    decision
uint16 STAND                = 25
uint16 HAND_SHAKE           = 26
uint16 BACK                 = 27

#    camera
uint16 FACE_SCAN            = 30
uint16 FACE_OK              = 31
uint16 FACE_FAILED          = 32
uint16 FACE_FOLLOW_BEGIN    = 33
uint16 FACE_FOLLOW_SCAN     = 34
uint16 FACE_FOLLOW_SCAN_OK  = 35

#---alarm---






#---notice---
#    power
uint16 LOW_POWER_T          = 50
uint16 CHARGE_START_T       = 51
uint16 CHARGEING_T          = 52
uint16 CHARGED_T            = 53

#    blue
uint16 BLUE_FAILED_T        = 60
uint16 BLUE_CONNECTING_T    = 61
uint16 BLUE_SUCCEED_T       = 62

#    wifi
uint16 WIFI_CONNECTING_T    = 65
uint16 WIFI_FAILED_T        = 66

#    decision
uint16 HAND_SHAKE_T         = 70

#---interaction---

uint16 FACE_ONE_PERSON      = 600
uint16 FACE_STAY_STILL      = 601
uint16 FACE_FRONT_KEEP      = 602
uint16 FACE_NEAR_SMALL      = 603

uint16 FACE_STAND_STILL_T   = 604
uint16 FACE_SUCCEED_T       = 605
uint16 FACE_FAILED_T        = 606
uint16 FACE_FOLLOW_BEGIN_T  = 607
uint16 FACE_FOLLOW_SCAN_T   = 608

uint16 WALK_FAR_WAIT        = 620
uint16 WALK_FAST_WAIT       = 621
uint16 WALK_FLOW_LOST       = 622
uint16 WALK_CHANGE_ROUTE    = 623
uint16 WALK_OBSTACLE        = 624
uint16 WALK_KEEP_DISTANCE   = 625
uint16 WALK_EMERGENCY_STOP  = 626

#---assistant---
uint16 XIAOAI_ONLINE_NOTICE = 650
uint16 WAKE_BARK            = 651
uint16 TTS_NO               = 652

uint16 id



