
[[step]]
type     = "transition"
height   = [0.3]
duration = [300.0]

[[step]]
type     = "locomotion"
vel      = [0.0, 0.0, 0.0]
omni     = [0.0]
gait     = [10.0]
duration = [2625.0]

[[step]]
type     = "transition"
height   = [0.3]
duration = [375.0]

[[step]]
type     = "locomotion"
vel      = [0.0, 0.0, 0.0]
omni     = [0.0]
gait     = [1.0]
duration = [2625.0]

[[step]]
type     = "transition"
height   = [0.3]
duration = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.4, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.8, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.8, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.4, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.35, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.7, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.7, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.35, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [375.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.2, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [108.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.04, -0.004, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.038, -0.012, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.035, -0.019, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.031, -0.026, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.025, -0.031, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.018, -0.036, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.011, -0.038, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.003, -0.04, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.005, -0.04, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.013, -0.038, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.02, -0.034, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.027, -0.03, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.032, -0.024, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.036, -0.017, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.039, -0.01, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.04, -0.002, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.039, 0.006, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.037, 0.014, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.034, 0.021, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.029, 0.027, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.023, 0.033, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.016, 0.037, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.008, 0.039, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.04, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.007, 0.039, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.015, 0.037, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.022, 0.033, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.028, 0.028, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.033, 0.022, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.037, 0.015, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.039, 0.007, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.017, 0.001, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [108.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [108.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.04, -0.004, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.038, -0.012, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.035, -0.019, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.031, -0.026, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.025, -0.031, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.018, -0.036, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.011, -0.038, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.003, -0.04, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.005, -0.04, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.013, -0.038, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.02, -0.034, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.027, -0.03, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.032, -0.024, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.036, -0.017, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.039, -0.01, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.04, -0.002, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.039, 0.006, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.037, 0.014, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.034, 0.021, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.029, 0.027, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.023, 0.033, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.016, 0.037, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.008, 0.039, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.04, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.007, 0.039, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.015, 0.037, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.022, 0.033, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.028, 0.028, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.033, 0.022, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.037, 0.015, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.039, 0.007, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, -0.016, 0.001, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [40.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, -0.2, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [-0.2, 0.0, 0.0]
duration     = [108.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.1, 0.4, 0.0, -0.08, -0.05, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [400.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.3, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [100.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [-0.6, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [200.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [0.3, 0.0, 0.0, 0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [100.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.02]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [100.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.3, 0.0, 0.26]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [200.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [100.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, -0.06]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [200.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.06]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [200.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, -0.06]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [200.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.06]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [200.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [100.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [-0.3, 0.0, -0.26]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [300.0]

[[step]]
type         = "pose"
foot_support = [1.0, -1.0, 1.0, 1.0]
body_cmd     = [0.0, 0.0, 0.0, -0.0, 0.0, 0.0]
foot_cmd     = [0.0, 0.0, -0.02]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [100.0]

[[step]]
type         = "pose"
foot_support = [1.0, 1.0, 1.0, 1.0]
body_cmd     = [-0.1, -0.4, 0.0, 0.08, 0.05, 0.0]
foot_cmd     = [0.0, 0.0, 0.0]
ctrl_point   = [0.0, 0.0, 0.0]
duration     = [400.0]

[[step]]
type     = "transition"
height   = [0.3]
duration = [1200.0]
