# Gait with timestamp
#
builtin_interfaces/Time timestamp
#
# Gait of robot
#
uint8 GAIT_DEFAULT   = 99
uint8 GAIT_TRANS     = 0
uint8 GAIT_PASSIVE   = 1
uint8 GAIT_KNEEL     = 2
uint8 GAIT_STAND_R   = 3
uint8 GAIT_STAND_B   = 4
uint8 GAIT_AMBLE     = 5
uint8 GAIT_WALK      = 6
uint8 GAIT_SLOW_TROT = 7
uint8 GAIT_TROT      = 8
uint8 GAIT_FLYTROT   = 9
uint8 GAIT_BOUND     = 10
uint8 GAIT_PRONK     = 11
#
uint8 gait