# Robot prebuilt order with timestamp
#
builtin_interfaces/Time timestamp
#
uint8 MONO_ORDER_NULL        =  0
uint8 MONO_ORDER_STAND_UP    =  9
uint8 MONO_ORDER_PROSTRATE   = 10
uint8 MONO_ORDER_STEP_BACK   = 12
uint8 MONO_ORDER_TURN_AROUND = 13
uint8 MONO_ORDER_HI_FIVE     = 14
uint8 MONO_ORDER_DANCE       = 15
uint8 MONO_ORDER_WELCOME     = 16
uint8 MONO_ORDER_TURN_OVER   = 17
uint8 MONO_ORDER_SIT         = 18
uint8 MONO_ORDER_SHOW        = 20
uint8 MONO_ORDER_LIST        = 14
#
uint8 id
float64 para
#
