uint8 SET_PARAMETERS = 0
uint8 TAKE_PICTURE = 1
uint8 START_RECORDING = 2
uint8 STOP_RECORDING = 3
uint8 GET_STATE = 4
uint8 DELETE_FILE = 5
uint8 GET_ALL_FILES = 6
uint8 START_LIVE_STREAM = 7
uint8 STOP_LIVE_STREAM = 8

uint8 command
string args
---
uint8 RESULT_SUCCESS = 0
uint8 RESULT_INVALID_ARGS = 1
uint8 RESULT_UNSUPPORTED = 2
uint8 RESULT_TIMEOUT = 3
uint8 RESULT_BUSY = 4
uint8 RESULT_INVALID_STATE = 5
uint8 RESULT_INNER_ERROR = 6
uint8 RESULT_UNDEFINED_ERROR = 255

uint8 result
string msg
