
[mode_list]
MODE_DEFAULT    = 0
MODE_LOCK       = 1
MODE_MANUAL     = 3
MODE_SEMI       = 13
MODE_EXPLOR     = 14
MODE_TRACK      = 15

[order_list]
MONO_ORDER_NULL        =  0
MONO_ORDER_STAND_UP    =  9
MONO_ORDER_PROSTRATE   = 10
MONO_ORDER_STEP_BACK   = 12
MONO_ORDER_TURN_AROUND = 13
MONO_ORDER_HI_FIVE     = 14
MONO_ORDER_DANCE       = 15
MONO_ORDER_WELCOME     = 16
MONO_ORDER_TURN_OVER   = 17
MONO_ORDER_SIT         = 18
MONO_ORDER_SHOW        = 20
MONO_ORDER_LIST        = 14
