[order_list]
MONO_ORDER_PROSTRATE   = 10
MONO_ORDER_STEP_BACK   = 12
MONO_ORDER_TURN_AROUND = 13
MONO_ORDER_HI_FIVE     = 14
MONO_ORDER_DANCE       = 15
MONO_ORDER_WELCOME     = 16
MONO_ORDER_TURN_OVER   = 17
MONO_ORDER_SIT         = 18
MONO_ORDER_SHOW        = 20
