axis = [4, 3, 1, 0]

[[button]] #0  Main_U
pos = 3
type = "B"
[[button]] #1  Main_D
pos = 0
type = "B"
[[button]] #2  Main_L
pos = 2
type = "B"
[[button]] #3  Main_R
pos = 1
type = "B"
[[button]] #4  Cross_U
down = 1
pos = 7
type = "A"
[[button]] #5  Cross_D
down = -1
pos = 7
type = "A"
[[button]] #6  Cross_L
down = 1
pos = 6
type = "A"
[[button]] #7  Cross_R
down = -1
pos = 6
type = "A"
[[button]] #8  Trig_R
pos = 5
type = "B"
[[button]] #9  Trig_RS
down = -1
pos = 5
type = "A"
[[button]] #10 Trig_L
pos = 4
type = "B"
[[button]] #11 Trig_LS
down = -1
pos = 2
type = "A"
[[button]] #12 Menu_R
pos = 7
type = "B"
[[button]] #13 Menu_L
pos = 6
type = "B"
[[button]] #14 Stick_R
pos = 10
type = "B"
[[button]] #15 Stick_L
pos = 9
type = "B"
